ProtocolType: DB migration to make name unique.
Otherwise we get this:

```
thread 'storage::postgres::protocol::test::test_add_protocol_type' panicked at tycho-indexer/src/storage/postgres/protocol.rs:181:14:
called `Result::unwrap()` on an `Err` value: Unexpected("there is no unique or exclusion constraint matching the ON CONFLICT specification")
```